import { describe, expect, it } from "vitest";
import { buildReadinessCommandCenter } from "@/lib/readiness";
import { createDemoEvent, getDashboardSnapshot, ingestResourceEvent, resetState } from "@/lib/store";

describe("Readiness Command Center", () => {
  it("exposes marketable, rule-aware readiness surfaces", async () => {
    resetState();
    await ingestResourceEvent(createDemoEvent("public-secret"));

    const readiness = buildReadinessCommandCenter(getDashboardSnapshot());

    expect(readiness.usp).toContain("One-day Google Workspace risk scan");
    expect(readiness.pilotLaunchPlan.offer).toContain("$199 one-day Google Workspace risk scan");
    expect(readiness.pilotLaunchPlan.checklist.length).toBeGreaterThanOrEqual(10);
    expect(readiness.pilotLaunchPlan.blockers.join(" ")).toContain("Live Workspace OAuth");
    expect(readiness.oauthReadiness.mode).toBe("pilot-test-users");
    expect(readiness.oauthReadiness.requiredScopes.some((scope) => scope.sensitivity === "restricted")).toBe(true);
    expect(readiness.persistenceReadiness.writePlan.map((item) => item.target)).toContain("bigquery");
    expect(readiness.persistenceReadiness.tenantIsolation.firestoreRoot).toContain("tenant_mainstreet_security");
    expect(readiness.syncReliability.reconciliationCadenceHours).toBeGreaterThan(0);
    expect(readiness.syncReliability.driveCursor).toContain("mock_drive");
    expect(readiness.syncReliability.gmailCursor).toBe("1234567890");
    expect(readiness.syncReliability.reliabilityNotes.join(" ")).toContain("users.history.list");
    expect(readiness.riskTrend.history.length).toBeGreaterThanOrEqual(2);
    expect(readiness.riskTrend.productionWarning).toContain("Firestore/BigQuery");
    expect(readiness.xprizeGate.overallStatus).toBe("blocked");
    expect(readiness.xprizeGate.checks.length).toBeGreaterThanOrEqual(10);
    expect(readiness.xprizeGate.blockingSummary.join(" ")).toContain("Deploy");
    expect(readiness.submissionCompliance.overallStatus).toBe("blocked");
    expect(readiness.submissionCompliance.checks.map((check) => check.id)).toContain("third-party-license-manifest");
    expect(readiness.submissionCompliance.demoAssetChecklist.length).toBeGreaterThanOrEqual(5);
    expect(readiness.devpostSubmissionPack.overallStatus).toBe("blocked");
    expect(readiness.devpostSubmissionPack.demoVideoScript).toHaveLength(6);
    expect(readiness.devpostSubmissionPack.screenshotChecklist.map((item) => item.id)).toContain("devpost-pack");
    expect(readiness.demoVideoCompliance.overallStatus).toBe("blocked");
    expect(readiness.demoVideoCompliance.plannedDurationSeconds).toBe(175);
    expect(readiness.demoVideoCompliance.checks.map((check) => check.id)).toContain("live-gemini-proof-scene");
    expect(readiness.productionLaunch.overallStatus).toBe("blocked");
    expect(readiness.productionLaunch.workstreams.map((item) => item.id)).toContain("gcp-deploy-persistence");
    expect(readiness.productionLaunch.verificationCommands.map((item) => item.id)).toContain("persistence-write-through");
    expect(readiness.marketPositioning.overallStatus).toBe("needs-proof");
    expect(readiness.marketPositioning.competitorComparisons.map((item) => item.name)).toEqual(["Vanta", "Drata", "Secureframe"]);
    expect(readiness.pilotCrm.some((pilot) => pilot.armsLength && !pilot.relatedParty)).toBe(true);
    expect(readiness.pilotProspectPipeline.summary.highFit).toBeGreaterThanOrEqual(3);
    expect(readiness.pilotProspectPipeline.summary.proposedPilots).toBeGreaterThanOrEqual(1);
    expect(readiness.pilotProspectPipeline.blockers.join(" ")).toContain("production");
    expect(readiness.pilotConversionKit.offer).toContain("$199 one-day Google Workspace risk scan");
    expect(readiness.pilotConversionKit.status).toBe("blocked");
    expect(readiness.pilotConversionKit.conversionSteps.map((step) => step.id)).toContain("invoice-payment");
    expect(readiness.pilotConversionKit.closeAssets.map((asset) => asset.id)).toContain("founder-email");
    expect(readiness.pilotConversionKit.evidenceChecklist.map((item) => item.id)).toContain("payment-export");
    expect(readiness.pilotConversionKit.blockers.join(" ")).toContain("SENTINEL_EVIDENCE_MODE");
    expect(readiness.pilotConsentPacket.packetTitle).toContain("consent and scope packet");
    expect(readiness.pilotConsentPacket.oauthScopes.find((scope) => scope.scope === "https://www.googleapis.com/auth/drive")?.status).toBe("deferred");
    expect(readiness.pilotConsentPacket.consentChecklist.map((item) => item.evidenceArtifactKind)).toContain("pilot-consent");
    expect(readiness.financialEvidence.evidenceMode).toBe("mock");
    expect(readiness.financialEvidence.summary["mock-only"]).toBeGreaterThan(0);
    expect(readiness.financialEvidence.summary.missing).toBeGreaterThan(0);
    expect(readiness.financialEvidence.blockers.join(" ")).toContain("invoice/payment proof");
    expect(readiness.evidenceVault.requiredArtifacts.length).toBeGreaterThanOrEqual(15);
    expect(readiness.evidenceVault.summary.missing).toBeGreaterThan(0);
    expect(readiness.evidenceVault.blockers.join(" ")).toContain("Evidence Vault artifacts");
    expect(readiness.evidenceIntakeQueue.overallStatus).toBe("blocked");
    expect(readiness.evidenceIntakeQueue.items.map((item) => item.kind)).toContain("pilot-invoice");
    expect(readiness.evidenceIntakeQueue.criticalMissing).toBeGreaterThan(0);
    expect(readiness.aiCostGuardrail.modelAllowlist).toContain("gemini-3.5-flash");
    expect(readiness.cloudCostControls.status).toBe("blocked");
    expect(readiness.cloudCostControls.budgetPlan.alertThresholds.length).toBeGreaterThanOrEqual(4);
    expect(readiness.cloudCostControls.apiKeyRestrictionPlan.requiredApiTargets).toContain(
      "generativelanguage.googleapis.com"
    );
    expect(readiness.claimGuard.status).toBe("passed");
    expect(readiness.claimGuard.bannedClaims).toContain("guaranteed compliance");
    expect(readiness.complianceCopyGuardrail.bannedClaims).toContain("SOC2 certified");
    expect(readiness.approvalQueue.pending + readiness.approvalQueue.dueSoon + readiness.approvalQueue.overdue).toBeGreaterThanOrEqual(1);
    expect(readiness.approvalQueue.earliestDueAt).toBeDefined();
    expect(readiness.approvalQueue.escalationTargets).toContain("founder@mainstreet-security.example");
    expect(readiness.approvalOps.directory.length).toBeGreaterThanOrEqual(4);
    expect(readiness.approvalOps.assignedApprovals).toBeGreaterThanOrEqual(1);
    expect(readiness.approvalOps.queuedNotifications).toBeGreaterThanOrEqual(1);
    expect(readiness.approvalOps.productionGaps.join(" ")).toContain("production email");
    expect(readiness.trustAnalytics.packetsCreated).toBeGreaterThanOrEqual(0);
    expect(readiness.trustAnalytics.productionGaps.join(" ")).toContain("Firestore/BigQuery");
    expect(readiness.frameworkCoverage.map((item) => item.framework)).toEqual(["SOC2", "ISO 27001", "GDPR", "HIPAA", "PCI"]);
    expect(readiness.playbooks.length).toBeGreaterThanOrEqual(3);
    expect(readiness.playbooks.every((playbook) => playbook.tenantId === "tenant_mainstreet_security")).toBe(true);
    expect(readiness.playbooks.some((playbook) => playbook.ownerRole === "legal")).toBe(true);
    expect(readiness.roiCalculator.paybackMultiple).toBeGreaterThan(1);
    expect(readiness.judgeNarrative.threeMinuteScript).toHaveLength(5);
  });
});
